Student Name: Poorva Araj
Id: 000997514

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score
from sklearn.model_selection import GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
np.random.seed(0)


In [ ]:
import sklearn.model_selection
import spacy
import matplotlib.pyplot as plt
import seaborn as sns 
from time import time

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report

In [ ]:
import nltk

In [ ]:
#!pip install nltk.tokenize

In [ ]:
from IPython.display import HTML
def pretty_print_df(value_counts_):
  "Quick function to display value counts more nicely"
  display(HTML(pd.DataFrame(value_counts_).to_html()))


In [ ]:
from google.colab import files
import io

uploaded = files.upload()    # Will prompt you to select file
df = pd.read_csv(io.BytesIO(uploaded['processed_reviews_split_surnamesA_minimal.csv']))


Saving processed_reviews_split_surnamesA_minimal.csv to processed_reviews_split_surnamesA_minimal (1).csv


In [ ]:
df.head()


review_id                                               text  \
0  product_review_000000                                 guitars look new.    
1  product_review_000001  I'd heard this game had crude humor, but man i...   
2  product_review_000002  It's a decent game but nothing nearly as good ...   
3  product_review_000003  This device worked exceptionally well for my X...   
4  product_review_000004  great racing game, with a lot of cool cars to ...   

  verified  review_score     product_category  
0    False           5.0  musical_instruments  
1     True           4.0          video_games  
2     True           4.0          video_games  
3    False           5.0          video_games  
4     True           4.0          video_games

In [ ]:
print(df.shape)

(32918, 5)


In [ ]:
df.describe()

review_score
count  32918.000000
mean       4.088098
std        1.434291
min       -1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

In [ ]:
df1 = df.filter(['text','review_score'],axis=1)

In [ ]:
df1.head()

text  review_score
0                                 guitars look new.            5.0
1  I'd heard this game had crude humor, but man i...           4.0
2  It's a decent game but nothing nearly as good ...           4.0
3  This device worked exceptionally well for my X...           5.0
4  great racing game, with a lot of cool cars to ...           4.0

In [ ]:
df1.tail()

text  review_score
32913  OVERALL: This game is a must-buy by all standa...           5.0
32914  I must say that I have all but given up on Son...           4.0
32915  After considering various options for my 1976 ...           5.0
32916  We have had this for 1 day. But the charger it...           4.0
32917  Easy to work with and sounds good.. Good price...           4.0

In [ ]:
print(df1.shape)

(32918, 2)


In [ ]:
df1.describe()

review_score
count  32918.000000
mean       4.088098
std        1.434291
min       -1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

In [ ]:
len(df1)

32918

In [ ]:
df1.isnull().sum()


text            12
review_score     0
dtype: int64

In [ ]:
df1['text'].isnull().sum()


12

In [ ]:
df1 = df1[pd.notnull(df1["text"])]

In [ ]:
len(df1)

32906

In [ ]:
df1['review_score'].value_counts()

 5.0    19239
 4.0     6209
 3.0     3153
 1.0     1860
 2.0     1538
-1.0      907
Name: review_score, dtype: int64

In [ ]:
df1['review_score'] = df1['review_score'].replace([-1.0],1.0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
df1['review_score'].value_counts()

5.0    19239
4.0     6209
3.0     3153
1.0     2767
2.0     1538
Name: review_score, dtype: int64

In [ ]:
print(df1.shape[1])

2


In [ ]:
tfidf = TfidfVectorizer(max_df=0.5, min_df= 10,stop_words="english",  ngram_range=(1,5), analyzer='char')


In [ ]:
X1= tfidf.fit_transform(df1['text'].values.astype('U')) # astype('U') converts string data to unicode
y1=df1['review_score']

In [ ]:
print(X1.shape[1])

156534


In [ ]:
X1.shape, y1.shape

((32906, 156534), (32906,))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.2, 
                                                    shuffle= True, random_state=42)



In [ ]:
X_train.shape

(26324, 156534)

In [ ]:
X_test.shape

(6582, 156534)

In [ ]:
y_train.shape

(26324,)

In [ ]:
y_test.shape

(6582,)

In [ ]:
clf = LinearSVC(C=20, class_weight='balanced' ) #c=10 is regularization



In [ ]:
clf.fit(X_train, y_train )

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,


LinearSVC(C=20, class_weight='balanced')

In [ ]:
y_pred= clf.predict(X_test)

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         1.0       0.39      0.36      0.37       571
         2.0       0.36      0.23      0.28       316
         3.0       0.40      0.36      0.38       654
         4.0       0.41      0.40      0.41      1297
         5.0       0.76      0.81      0.79      3744

    accuracy                           0.62      6582
   macro avg       0.46      0.43      0.45      6582
weighted avg       0.60      0.62      0.61      6582



In [ ]:
real_review = 'product is good'
vec = tfidf.transform([real_review])
clf.predict(vec)

array([4.])

In [ ]:
real_review2 = 'product is okay. '
vec2 = tfidf.transform([real_review2])
clf.predict(vec2)

array([3.])

In [ ]:
real_review3 = 'I loved it'
vec3 = tfidf.transform([real_review3])
clf.predict(vec3)

array([5.])

In [ ]:
real_review4 = 'amazing product. Must-buy'
vec4 = tfidf.transform([real_review4])
clf.predict(vec4)

array([5.])

TASK 2


In [ ]:
#!pip install --upgrade spacy

In [ ]:
#!python -m spacy download en_core_web_md

In [ ]:
#!python -m spacy download en_core_web_sm

In [ ]:
import sklearn.model_selection
import spacy
import matplotlib.pyplot as plt
import seaborn as sns 
from time import time

In [ ]:
# Create an NLP pipeline
nlp = spacy.load('en_core_web_md') 


In [ ]:
df.head()

review_id                                               text  \
0  product_review_000000                                 guitars look new.    
1  product_review_000001  I'd heard this game had crude humor, but man i...   
2  product_review_000002  It's a decent game but nothing nearly as good ...   
3  product_review_000003  This device worked exceptionally well for my X...   
4  product_review_000004  great racing game, with a lot of cool cars to ...   

  verified  review_score     product_category  
0    False           5.0  musical_instruments  
1     True           4.0          video_games  
2     True           4.0          video_games  
3    False           5.0          video_games  
4     True           4.0          video_games

In [ ]:
df2 = df.filter(['text','product_category'],axis=1)

In [ ]:
df2.head()

text     product_category
0                                 guitars look new.   musical_instruments
1  I'd heard this game had crude humor, but man i...          video_games
2  It's a decent game but nothing nearly as good ...          video_games
3  This device worked exceptionally well for my X...          video_games
4  great racing game, with a lot of cool cars to ...          video_games

In [ ]:
df2.isnull().sum()

text                 12
product_category    906
dtype: int64

In [ ]:
df2 = df2[pd.notnull(df2["text"])]

In [ ]:
df2 = df2[pd.notnull(df2["product_category"])]

In [ ]:
print(df2.shape)

(32000, 2)


In [ ]:
df2['product_category'].value_counts()

video_games            21727
musical_instruments    10273
Name: product_category, dtype: int64

In [ ]:
#Transforming dataset column "text" in lowercase
df2["text"]=df2["text"].str.lower()

In [ ]:
import re
import string

In [ ]:
#removing punctuations
df2['text'] = df2['text'].apply(lambda x: re.sub('[%s]' % re.escape(string.punctuation), '' , x))

In [ ]:
#removing digits from "text" reviews
df2['text'] = df2['text'].apply(lambda x: re.sub('W*dw*','',x))

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
from nltk.corpus import stopwords

In [ ]:
#removing stopwords
stop_words = set(stopwords.words('english'))
def remove_stopwords(text):
    return " ".join([word for word in str(text).split() if word not in stop_words])
df2['text'] = df2['text'].apply(lambda x: remove_stopwords(x))

In [ ]:
from nltk.stem import WordNetLemmatizer

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [ ]:
#lemmatization
lemmatizer = WordNetLemmatizer()
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])
df2["text"] = df2["text"].apply(lambda text: lemmatize_words(text))
 

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
labelencoder = LabelEncoder()
df2['num_categories']= labelencoder.fit_transform(df2['product_category'])

In [ ]:
df2.head()

text     product_category  \
0                                    guitar look new  musical_instruments   
1  hear game ha crue humor man worse expecte love...          video_games   
2  ecent game nothing nearly goo orginal game gre...          video_games   
3  evice worke exceptionally well xbox 360 work g...          video_games   
4  great racing game lot cool car rive favorite m...          video_games   

   num_categories  
0               0  
1               1  
2               1  
3               1  
4               1

In [ ]:
print(df2['num_categories'].value_counts())
print("0 : Musical Instruments and 1 : Video Games")

1    21727
0    10273
Name: num_categories, dtype: int64
0 : Musical Instruments and 1 : Video Games


In [ ]:
training_data = df2.sample(frac=0.8, random_state=25)
testing_data = df2.drop(training_data.index)

print(f"No. of training examples: {training_data.shape[0]}")
print(f"No. of testing examples: {testing_data.shape[0]}")

No. of training examples: 25600
No. of testing examples: 6400


In [ ]:
training_data['num_categories'].value_counts()

1    17306
0     8294
Name: num_categories, dtype: int64

In [ ]:
testing_data['num_categories'].value_counts()

1    4421
0    1979
Name: num_categories, dtype: int64

In [ ]:
vectorizer = TfidfVectorizer(max_df=0.5, min_df= 10, stop_words="english", 
                             ngram_range= (1,3), analyzer='char')#, sublinear_tf=True)
# fit on and apply to training data
X_trainn = vectorizer.fit_transform(training_data['text'].values.astype('U'))

# apply to test data
X_testt = vectorizer.transform(testing_data['text'])

#print the number of features
print(X_trainn.shape[1])

# print average number of non-zero features for each document
X_trainn.nnz / float(X_trainn.shape[0])



7716


278.360859375

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score
from sklearn.model_selection import GridSearchCV


In [ ]:
import warnings
warnings.simplefilter("ignore") # 
#for GridSearchCV: because some of its combination throws warning 


In [ ]:
y_trainn = training_data['num_categories']
y_testt = testing_data['num_categories'] 

In [ ]:
param_grid=[{'C': np.logspace(-4,4,15)}, #inverse of regularization strength
           {'penalty': ['l1', 'l2']},
           {'solver': ['lbfgs', 'liblinear', 'adam']}, 
          {'max_iter': [10000]}] #we set this low to speed things up


In [ ]:
lr = LogisticRegression(class_weight='balanced')


In [ ]:
grid = GridSearchCV(estimator=lr, param_grid=param_grid, cv=10, scoring='recall', refit=True) # you can change scoring function that will impact the estimator
grid = grid.fit(X_trainn, y_trainn)
print('Best estimator: {}\nWeights: {}, Intercept: {}\nBest params: {}\nScorer: {}'.format(grid.best_estimator_, grid.best_estimator_.coef_, grid.best_estimator_.intercept_,grid.best_params_, grid.scorer_))
print('Available parameters for the estimator (fine-tuning): ',lr.get_params().keys())


Best estimator: LogisticRegression(C=10000.0, class_weight='balanced')
Weights: [[ 4.42517827 -4.35709335 -7.95380735 ... 12.29215736 14.63506943
   8.30389514]], Intercept: [0.02009409]
Best params: {'C': 10000.0}
Scorer: make_scorer(recall_score, average=binary)
Available parameters for the estimator (fine-tuning):  dict_keys(['C', 'class_weight', 'dual', 'fit_intercept', 'intercept_scaling', 'l1_ratio', 'max_iter', 'multi_class', 'n_jobs', 'penalty', 'random_state', 'solver', 'tol', 'verbose', 'warm_start'])


In [ ]:

def evaluate_classifier(grid, X_trainn, y_trainn, X_testt, y_testt):
    # model evaluation for training set
    y_train_predict = grid.predict(X_trainn)
    print("Training SET")
    print("--------------------------------------")
    print('Accuracy: {:.3f}, Precision: {:.3f}, Recall: {:.3f}, F1 Score: {:.3f}'.format(accuracy_score(y_trainn, y_train_predict), 
                                                                                        precision_score(y_trainn, y_train_predict), 
                                                                                        recall_score(y_trainn, y_train_predict), 
                                                                                        f1_score(y_trainn, y_train_predict)))
    print("Confusion Matrix:\n {}".format(confusion_matrix(y_trainn, y_train_predict)))

    # model evaluation for testing set
    y_test_predict = grid.predict(X_testt)

    print("\nTesting SET")
    print("--------------------------------------")
    print('Accuracy: {:.3f}, Precision: {:.3f}, Recall: {:.3f}, F1 Score: {:.3f}'.format(accuracy_score(y_testt, y_test_predict), 
                                                                                        precision_score(y_testt, y_test_predict), 
                                                                                        recall_score(y_testt, y_test_predict), 
                                                                                        f1_score(y_testt, y_test_predict)))
    print("Confusion Matrix:\n {}".format(confusion_matrix(y_testt, y_test_predict)))
    return y_train_predict, y_test_predict

y_train_predict, y_test_predict = evaluate_classifier(grid, X_trainn, y_trainn, X_testt, y_testt)


Training SET
--------------------------------------
Accuracy: 0.981, Precision: 0.995, Recall: 0.978, F1 Score: 0.986
Confusion Matrix:
 [[ 8205    89]
 [  385 16921]]

Testing SET
--------------------------------------
Accuracy: 0.918, Precision: 0.948, Recall: 0.933, F1 Score: 0.940
Confusion Matrix:
 [[1753  226]
 [ 296 4125]]
